typography_spectrum: 0.1914894
color:
  saturation: 0.2514543703291565
  brandStrength: 1
  lightness: 0.8278653980232775
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  rhythmicContrast: 0.86377790174447
layout_spectrum: 1
name: yeelog
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: hey ho let's go
